package org.pnm.dun.unit;

public enum ActiveType {
	OPPORTUNITY_ATTACK, CHARM, BUFF, HEAL, POWER, DEBUFF, PRAYER, RAGE, CLEAVE, SHIFT, CRIP_SHOT, RAPID_SHOT, EVADE, CALL_SHOT, TWIN_STRIKE, SMASH, FIREBALL, SLAM, BASIC
}
